///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Ranorex_EOH_Demo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddToBasket recording.
    /// </summary>
    [TestModule("181e5bfc-bd64-4229-b2ee-2d25dfa320f6", ModuleType.Recording, 1)]
    public partial class AddToBasket : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Ranorex_EOH_DemoRepository repository.
        /// </summary>
        public static Ranorex_EOH_DemoRepository repo = Ranorex_EOH_DemoRepository.Instance;

        static AddToBasket instance = new AddToBasket();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddToBasket()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddToBasket Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CapEdgewordsShop.AddToCart' at 73;27.", repo.CapEdgewordsShop.AddToCartInfo, new RecordItemIndex(0));
            repo.CapEdgewordsShop.AddToCart.Click("73;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=' “Cap” has been added to your cart.') on item 'CapEdgewordsShop.DivTagCapHasBeenAddedToYourCart'.", repo.CapEdgewordsShop.DivTagCapHasBeenAddedToYourCartInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.CapEdgewordsShop.DivTagCapHasBeenAddedToYourCartInfo, "InnerText", " “Cap” has been added to your cart.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CapEdgewordsShop.ViewCart' at 59;15.", repo.CapEdgewordsShop.ViewCartInfo, new RecordItemIndex(2));
            repo.CapEdgewordsShop.ViewCart.Click("59;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Src='https://www.edgewordstraining.co.uk/demo-site/wp-content/uploads/2018/03/cap.jpg') on item 'CartEdgewordsShop.HttpsWwwEdgewordstrainingCoUkDemo'.", repo.CartEdgewordsShop.HttpsWwwEdgewordstrainingCoUkDemoInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.CartEdgewordsShop.HttpsWwwEdgewordstrainingCoUkDemoInfo, "Src", "https://www.edgewordstraining.co.uk/demo-site/wp-content/uploads/2018/03/cap.jpg");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
