///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Ranorex_EOH_Demo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Ranorex_EOH_DemoRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    [RepositoryFolder("2c810a72-6ab7-4e4e-a2de-b0ec28e8f87f")]
    public partial class Ranorex_EOH_DemoRepository : RepoGenBaseFolder
    {
        static Ranorex_EOH_DemoRepository instance = new Ranorex_EOH_DemoRepository();

        /// <summary>
        /// Gets the singleton class instance representing the Ranorex_EOH_DemoRepository element repository.
        /// </summary>
        [RepositoryFolder("2c810a72-6ab7-4e4e-a2de-b0ec28e8f87f")]
        public static Ranorex_EOH_DemoRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Ranorex_EOH_DemoRepository() 
            : base("Ranorex_EOH_DemoRepository", "/", null, 0, false, "2c810a72-6ab7-4e4e-a2de-b0ec28e8f87f", ".\\RepositoryImages\\Ranorex_EOH_DemoRepository2c810a72.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("2c810a72-6ab7-4e4e-a2de-b0ec28e8f87f")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    public partial class Ranorex_EOH_DemoRepositoryFolders
    {
    }
#pragma warning restore 0436
}