///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Ranorex_EOH_Demo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The RemoveFromBasket recording.
    /// </summary>
    [TestModule("6696f77e-e433-4321-a565-5742898c32db", ModuleType.Recording, 1)]
    public partial class RemoveFromBasket : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Ranorex_EOH_DemoRepository repository.
        /// </summary>
        public static Ranorex_EOH_DemoRepository repo = Ranorex_EOH_DemoRepository.Instance;

        static RemoveFromBasket instance = new RemoveFromBasket();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public RemoveFromBasket()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static RemoveFromBasket Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CartEdgewordsShop.RemoveItem' at 22;22.", repo.CartEdgewordsShop.RemoveItemInfo, new RecordItemIndex(0));
            repo.CartEdgewordsShop.RemoveItem.Click("22;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CartEdgewordsShop.ATagReturnToShop' at 71;26.", repo.CartEdgewordsShop.ATagReturnToShopInfo, new RecordItemIndex(1));
            repo.CartEdgewordsShop.ATagReturnToShop.Click("71;26");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
