///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Ranorex_EOH_Demo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Search recording.
    /// </summary>
    [TestModule("904d72ff-5ba0-457e-9d08-7e09409ef493", ModuleType.Recording, 1)]
    public partial class Search : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Ranorex_EOH_DemoRepository repository.
        /// </summary>
        public static Ranorex_EOH_DemoRepository repo = Ranorex_EOH_DemoRepository.Instance;

        static Search instance = new Search();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Search()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Search Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EdgewordsShopECommerceDemoSiteFor.WoocommerceProductSearchField0' at 76;28.", repo.EdgewordsShopECommerceDemoSiteFor.WoocommerceProductSearchField0Info, new RecordItemIndex(0));
            repo.EdgewordsShopECommerceDemoSiteFor.WoocommerceProductSearchField0.Click("76;28");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'cap{Return}' with focus on 'EdgewordsShopECommerceDemoSiteFor.WoocommerceProductSearchField0'.", repo.EdgewordsShopECommerceDemoSiteFor.WoocommerceProductSearchField0Info, new RecordItemIndex(1));
            repo.EdgewordsShopECommerceDemoSiteFor.WoocommerceProductSearchField0.PressKeys("cap{Return}");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
